version: '3.7'

services:
  db:
    image: postgres:15
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432

  redis:
    image: redis:7
    command: redis-server --requirepass "$REDIS_PASS"
    environment:
      REDIS_PASS: ${REDIS_PASS}
    ports:
      - 6379:6379

  nginx:
    image: nginx:1.23.3
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:8080

  server:
    depends_on:
      - db
      - redis
    build:
      context: .
      dockerfile: Dockerfile.dev
    command:
      - /bin/sh
      - -c
      - |
        npx prisma generate --schema=./server/prisma/schema.prisma
        npm run start:server
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - 3000:3000

  portal:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command:
      - /bin/sh
      - -c
      - |
        npm run start:portal
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - 3001:3001

volumes:
  db_data:
  node_modules:
