version: '3.7'

services:
  db:
    image: postgres:15
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432

  redis:
    image: redis:7
    command: redis-server --requirepass "$REDIS_PASS"
    environment:
      REDIS_PASS: ${REDIS_PASS}

volumes:
  db_data:
